name: Run release scripts
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get all git tags
        run: |
          git fetch -f --prune --unshallow --tags

      - name: Set env variables
        run: |
          echo "version=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
          echo "prepare_log_path=./logs/prepare.txt" >> $GITHUB_ENV
          echo "build_log_path=./logs/build.txt" >> $GITHUB_ENV

      - name: Run preparebuild
        run: |
          sh ./scripts/prepareBuild.sh
        env:
          REPO: ${{ github.repository }}
          X_ORG_ID: ${{ secrets.X_ORG_ID }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          LOG_PATH: ${{ github.prepare_log_path }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: |
          sh ./scripts/buildDockerImage.sh
        env:
          VERSION: ${{ github.version }}
          LOG_PATH: ${{ github.build_log_path }}
          X_ORG_ID: ${{ secrets.X_ORG_ID }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          REPO: ${{ github.repository }}

      - uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: ./logs/build.txt

      - name: Run tests
        uses: actions/setup-node@v1
        with:
          node-version: '12'
        run: |
          npm ci
          sh ./scripts/runTests.sh
        env:
          VERSION: ${{ github.version }}
          X_ORG_ID: ${{ secrets.X_ORG_ID }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          REPO: ${{ github.repository }}

      - uses: actions/upload-artifact@v2
        with:
          name: tests-results
          path: testResults.json


