name: Run release scripts
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Fetch all tags
        run: |
          git fetch -f --prune --unshallow --tags

      - name: Create issue
        run: |
          sh ./scripts/createIssue.sh
        env:
          REPO: ${{ github.repository }}
          X_ORG_ID: ${{ secrets.X_ORG_ID }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: create-issue-log
          path: createIssue.log

      - uses: actions/upload-artifact@v2
        with:
          name: release-issue
          path: releaseIssue.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: |
          sh ./scripts/buildDockerImage.sh
        env:
          X_ORG_ID: ${{ secrets.X_ORG_ID }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          REPO: ${{ github.repository }}

      - uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: buildLog.log

      - name: Run tests
        run: |
          npm ci
          sh ./scripts/runTests.sh
        env:
          X_ORG_ID: ${{ secrets.X_ORG_ID }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          REPO: ${{ github.repository }}

      - uses: actions/upload-artifact@v2
        with:
          name: tests-results
          path: testResults.json

      - uses: actions/upload-artifact@v2
        with:
          name: run-tests-log
          path: runTestsLog.log


